[workspace]
resolver = "3"
members = ["wakuwaku", "wakuwaku-entity", "wakuwaku-gate", "wakuwaku-iggy", "wakuwaku-proof"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/suitsu31-club/wakuwaku"
homepage = "https://github.com/suitsu31-club/wakuwaku"

[workspace.dependencies]
tokio = {version = "^1.53", features = ["full"]}
kanau = {version = "0.6", features = ["message"]}
